### ISSUE TITLE
pretrained checkpoint

### ISSUE THREAD

**Issue by xuliu-cyber** [Meng-333/SRADSGAN#1]
Hello, can you share the pre-trained models? Thanks!

**Comment by Meng-333** [comment]
No problem, what is it used for? What scale factor is needed for the pre-trained model?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Meng-333/SRADSGAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月12日(星期五) 下午5:32
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Meng-333/SRADSGAN] pretrained checkpoint (Issue #1)





 
Hello, can you share the pre-trained models? Thanks!

**Comment by xuliu-cyber** [comment]
I am currently doing research on semantic segmentation of remote sensing images and would like to use some super-resolution algorithms to improve the resolution of the images. I want to try the model with a scale factor of 4.
Thanks!

**Comment by Meng-333** [comment]
想法很好，但感觉会有一定困难，祝你一切顺利！x4的checkpoint&nbsp;我周一返校后发你哈。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Meng-333/SRADSGAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月13日(星期六) 上午10:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Meng-333/SRADSGAN] pretrained checkpoint (Issue #1)





 
I am currently doing research on semantic segmentation of remote sensing images and would like to use some super-resolution algorithms to improve the resolution of the images. I want to try the model with a scale factor of 4.
 Thanks!

**Comment by xuliu-cyber** [comment]
好的，感谢~

**Comment by Meng-333** [comment]
请访问以下链接哈：https://wx.mail.qq.com/ftn/download?func=3&amp;key=9bcf14623a2153a5a9bc4a623334663465f0cc6031346634411f1c16095553005655490754015f19075455041c070307521d06510551070c5200050755567934174205064253075a3b48503d565108511651100d436b16551651094c415f0a2097c908d7eb2d5045a886237004b96f16d15ef2b1&amp;code=d0db14f4&amp;k=9bcf14623a2153a5a9bc4a623334663465f0cc6031346634411f1c16095553005655490754015f19075455041c070307521d06510551070c5200050755567934174205064253075a3b48503d565108511651100d436b16551651094c415f0a2097c908d7eb2d5045a886237004b96f16d15ef2b1&amp;fweb=1&amp;cl=1




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Meng-333/SRADSGAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月13日(星期六) 下午5:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Meng-333/SRADSGAN] pretrained checkpoint (Issue #1)





 
好的，感谢~

**Comment by xuliu-cyber** [comment]
点这个链接下载不了呀？

**Comment by Meng-333** [comment]
checkpoint: https://drive.google.com/drive/folders/1_ncUya30a-AwaDXkys56AMj2m8eSJjfH?usp=sharing
