### ISSUE TITLE
关于GPU

### ISSUE THREAD

**Issue by VMC-Lab-Chen** [Meng-333/SRADSGAN#2]
非常感觉作者杰出的工作，我是刚入门这个方向的新人，目前我手上能用的只有一张4090显卡，我想请问一下1张4090能否满足复现您代码的需求？

**Comment by Meng-333** [comment]
4090足够了，其实3090即可跑起来

**Comment by Superfish666** [comment]
好的感谢感谢，可以再请问一下4090完整训练一次大概需要多长时间？

**Comment by VMC-Lab-Chen** [comment]
好的感谢感谢，可以再请问一下4090完整训练一次大概需要多长时间吗？

**Comment by Meng-333** [comment]
其实也要看超分倍数，数据量，输入图像size这些参数；我的大概是2~3天

**Comment by VMC-Lab-Chen** [comment]
明白了，感谢大佬！祝科研顺利！
